# Generated by Django 4.2.6 on 2023-10-20 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exercise_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRealiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('exercises', models.ManyToManyField(through='core.ExerciseRealiation', to='core.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='exerciserealiation',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise'),
        ),
        migrations.AddField(
            model_name='exerciserealiation',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workout'),
        ),
    ]
