# Generated by Django 4.2.6 on 2023-10-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_exercise_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseRealiation',
            new_name='ExerciseRealization',
        ),
    ]
