# Generated by Django 4.2.6 on 2023-10-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_exerciserealiation_exerciserealization'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
