# Generated by Django 4.2.6 on 2023-10-28 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workout_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
