# Generated by Django 4.2.6 on 2023-11-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_workout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('weight_kg', models.FloatField()),
                ('rest_sec', models.IntegerField()),
                ('exercise_realization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exerciserealization')),
            ],
        ),
    ]
