# Generated by Django 4.2.6 on 2023-11-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_exerciseset_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exerciseset',
            constraint=models.UniqueConstraint(fields=('exercise_realization_id', 'order'), name='unique_exercise_realization_order'),
        ),
    ]
